secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt

services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop
    environment:
      PS_INSTALL_AUTO: 1
      PS_LANGUAGE: fr
      PS_COUNTRY: fr
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
      PS_DOMAIN: localhost:8080
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: admin
    secrets:
      - source: mysql_password
        target: DB_PASSWD
    ports:
      - "8080:80"
    volumes:
      - ps-volume:/var/www/html
    depends_on:
      - db
    networks:
      - ps-network

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: admin
    secrets:
      - mysql_root_password
      - mysql_password
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - ps-network
      - db-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "3307:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD_FILE: /run/secrets/mysql_root_password
      PMA_PMADB: phpmyadmin
    secrets:
      - mysql_root_password
    networks:
      - db-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:latest
    user: "1000:1000"
    ports:
      - "9100:9100"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_password
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring-network
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring-network

  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    container_name: mysql-backup
    volumes:
      - backup-volume:/backup
    secrets:
      - mysql_root_password
    networks:
      - db-network
    restart: unless-stopped

networks:
  ps-network:
  db-network:
  monitoring-network:

volumes:
  ps-volume:
  db-volume:
  grafana-volume:
  backup-volume:
